<?php
$page_name = "Privacy Policy";
//Privacy Policy Page Content
$html .= <<<EOD
		<h2>Privacy Policy</h2>		
			<div class='half-page faq'>			
			<p>Gun Values by Gun Digest holds our customers privacy as a very serious issue. We highly value our customers therefore we work hard to protect all of our customer's personal information by the latest security safeguards such as physical, electronic, and managerial procedures to safeguard and secure the information we collect online. Gun Values by Gun Digest is an online marketplace that allows our members to set up business and personal profiles that can be linked together through networks of contacts. Gun Values by Gun Digest members can view other profiles throughout various categories, communicate, post comments, and save members as contacts in their Gun Values member page. Members can display some personal address and contact information to other members and visitors, which allows our users to identify each other and expand their network of personal and business contacts. Gun Values by Gun Digest members can edit and change their profile and directory information at any time. </p>
			<h3>Information Collection and Use by Gun Values by Gun Digest</h3>
			<p>Gun Values by Gun Digest collects user submitted information such as name, email address, and age to authenticate users and to send notifications to those users relating to the Gun Values by Gun Digest service. Gun Values by Gun Digest also collects other profile data including but not limited to: personal interests, gender, age, education and occupation in order to assist users in finding and communicating with each other.</p>
			<p>Gun Values by Gun Digest also logs non-personally-identifiable information including IP address, profile information, aggregate user data, and browser type, from users and visitors to the site This data is used to manage the website, track usage and improve the website services. This non-personally-identifiable information may be shared with third-parties to provide more relevant services and advertisements to members. User IP addresses are recorded for security and monitoring purposes.</p>
			<p>User Profile information including members' pictures and business and personal names are displayed to people in order to facilitate user interaction in the Gun Values by Gun Digest social networking community. We may also use a user's email address to send updates, a newsletter or news regarding the service. Users may choose not to receive email of this type by changing their "notification" setting to "Do not send me notification emails" in the user "Account Settings" in the My Gun Values member area. </p>
			<p>	From time to time, Gun Values by Gun Digest or a partner, may sponsor a promotion, sweepstake or contest on Gun Values by Gun Digest. Users may be asked to provide personal information including name, email address or home address or to answer questions in order to participate. We may transfer personal information to certain ad partners that you have explicitly requested to receive information from. It will be clear at the point of collection who is collecting the personal information and whose privacy statement will apply.</p>
			<h3>Order Forms</h3>
			<p>Gun Values by Gun Digest uses order forms for customers to request information and services. We collect financial information such as user account information and credit card numbers. Financial information that is collected is used only to identify and bill the user for Gun Values by Gun Digest services. </p>
			<h3>Use of Cookies</h3>
			<p>Gun Values by Gun Digest uses cookies to store visitors' preferences and to record session information, for purposes including ensuring that visitors are not repeatedly offered the same advertisements and to customize newsletter, advertising, and Web page content based on browser type and user profile information. We do not link the information we store in cookies to any personally identifiable information you submit while on our site. You may be able to configure your browser to accept or reject all or some cookies, or notify you when a cookie is set -- each browser is different, so check the "Help" menu of your browser to learn how to change your cookie preferences -- however, you must enable cookies from Gun Values by Gun Digest in order to use most functions on the site Please note that Gun Values by Gun Digest allows 3rd party advertisers that are presenting advertisements on some of our pages to set and access their cookies on your computer. Advertisers' use of cookies is subject to their own privacy policies, not the Gun Values by Gun Digest Privacy Policy. </p>
			</div>
			<div class='half-page faq'>			
			<h3>Links </h3>
			<p>Gun Values by Gun Digest contains links to sites. Gun Values by Gun Digest is not responsible for the privacy policies and/or practices on other sites. When linking to another site a user should read the privacy policy stated on that site. Our privacy policy only governs information collected on Gun Values by Gun Digest. </p>
			<h3>Message Boards, Classifieds, Comments and Public Forums </h3>
			<p>Please be aware that whenever you voluntarily post public information to Message Boards, Classifieds or any other Public Forums that that information can be accessed by the public and can in turn be used by those people to send you unsolicited communications. </p>
			<h3>Correcting/Updating or Removing Information </h3>
			<p>Users may modify or remove any of their personal information at any time by logging into their account and accessing features such as Edit Profile and Account Info in the My Gun Values page. </p>
			<h3>Email Choice/Opt-out </h3>
			<p>Members who no longer wish to receive updates or notifications may choose not to by selecting 'Do not send me notification emails' in the Gun Values section 'Account Settings'. Users who do not wish to receive Gun Digest newsletters they may choose not to by using the instructions for opting-out of the newsletter communications in the future. </p>
			<h3>Third Party Advertising </h3>
			<p>Ads appearing on this Web site may be delivered to users by Gun Digest or one of our Web advertising partners. Our Web advertising partners may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement. In this way, ad servers may compile information about where you, or others who are using your computer, saw their advertisements and determine which ads are clicked on. This information allows an ad network to deliver targeted advertisements that they believe will be of most interest to you. This privacy statement covers the use of cookies by Gun Digest and does not cover the use of cookies by any advertisers. </p>
			<h3>Security </h3>
			<p>Gun Values by Gun Digest member accounts are secured by member-created passwords. Gun Values by Gun Digest takes precautions to insure that member account information is kept private. We use reasonable measures to protect member information that is stored within our database, and we restrict access to member information to those employees who need access to perform their job functions, such as our customer service personnel and technical staff. Please note that we cannot guarantee the security of member account information. Unauthorized entry or use, hardware or software failure, and other factors may compromise the security of member information at any time.</p>
			<h3>Sharing and Disclosure of Information Gun Values by Gun Digest Collects </h3>
			<p>Except as otherwise described in this privacy statement, Gun Values by Gun Digest will not disclose personal information to any third party unless we believe that disclosure is necessary: (1) to conform to legal requirements or to respond to a subpoena, search warrant or other legal process received by Gun Values by Gun Digest, whether or not a response is required by applicable law; (2) to enforce the Gun Values by Gun Digest Terms of Use Agreement or to protect our rights; or (3) to protect the safety of members of the public and users of the service. Gun Values by Gun Digest reserves the right to transfer personal information to a successor in interest that acquires rights to that information as a result of the sale of Gun Values by Gun Digest or substantially all of its assets to that successor in interest For more information see the "Changes in Privacy Policy" section below. </p>
			<h3>Changes in Privacy Policy </h3>
			<p>Gun Values by Gun Digest updates its privacy policy every once and awhile, if this occurs if we make changes, we post the changes so users will always be aware of what information we collect, how it is used, and when we may disclose it. </p>
			<h3>Contact us about our Privacy Policy </h3>
			<p>Contacting the Web Site Gun Values by Gun Digest cares deeply about online privacy, if you have any questions concerning this privacy statement, the practices of this site, or your dealings with this Web site, please contact us at: <a href="mailto:info@gundigest.com">info@gundigest.com</a>.</p>			
			</div>			
EOD;

?>



